apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - n3yron.nebula.video
    secretName: n3yron-tls
  rules:
   - host: n3yron.nebula.video
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: n3yron-svc
                port: 
                  number: 8080
# In case to check 443, TLS